### ISSUE TITLE
Unable to Install-Module Intune from PowerShell Gallery on Win10

### ISSUE THREAD

**Issue by scheblein** [Microsoft/Intune-PowerShell-SDK#1]
I'm trying to install the module in my Win 10 client and not in Cloud Shell.

A search for Intune at the PowerShell Gallery doesn't return a module named Intune: http://www.powershellgallery.com/items?q=Intune&x=0&y=0

I would hate to compile and install locally...

Results of attempt below:

```
PS C:\WINDOWS\system32> install-module Intune
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'Intune'. Try
Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS C:\WINDOWS\system32> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2/
```

**Comment by kevsully** [comment]
Hello, I'm trying to setup the module per the .md. I am getting an error that the PowerShellGraphSDK.dll can not be loaded.

`PS C:\scripts\net471> import-module .\Microsoft.Graph.Intune.psd1
import-module : Could not load file or assembly 'file:///C:\scripts\net471\Microsoft.Intune.PowerShellGraphSDK.dll' or one of its 
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ import-module .\Microsoft.Graph.Intune.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand`

I'm still working through this but wondering if there is a known issue here. RS5 build of Windows 10.

Thanks,
Kevin

**Comment by kevsully** [comment]
'ignore' apologize for this. I didn't get to the last comment in the .md file... it seems to be there.
