### ISSUE TITLE
officeSuiteApp missing

### ISSUE THREAD

**Issue by POF10** [Microsoft/Intune-PowerShell-SDK#11]
Hi guys,

Intune-PS is not returning Office Suite Apps.
Example:

```
$graphApiVersion = "Beta"
$Resource = "deviceAppManagement/mobileApps"
$uri = "https://graph.microsoft.com/$graphApiVersion/$($Resource)"
(Invoke-RestMethod -Uri $uri –Headers $authToken –Method Get).Value | ? { (!($_.'@odata.type').Contains("managed")) } | select "@odata.type"

@odata.type
-----------
#microsoft.graph.windowsMobileMSI
#microsoft.graph.windowsMobileMSI
#microsoft.graph.windowsMobileMSI
#microsoft.graph.officeSuiteApp
#microsoft.graph.windowsMobileMSI

```
Calling with PS module: 

```
Get-DeviceAppManagement_MobileApps | ? { (!($_.'@odata.type').Contains("managed")) } | s
elect "@odata.type"

@odata.type
-----------
#microsoft.graph.windowsMobileMSI
#microsoft.graph.windowsMobileMSI
#microsoft.graph.windowsMobileMSI
#microsoft.graph.windowsMobileMSI


```

However calling with precise AppID, it returns app as it should:

Get-DeviceAppManagement_MobileApps -mobileAppId '67248be8-2f1a-4992-bdea-7cd205174687'

```

@odata.context        : https://graph.microsoft.com/v1.0/$metadata#deviceAppManagement/mobileApps/$entity
id                    : 67248be8-2f1a-4992-bdea-7cd205174687
displayName           : Office 365 ProPlus
description           : 
publisher             : Microsoft
createdDateTime       : 8/9/2018 12:24:15 PM
lastModifiedDateTime  : 8/9/2018 12:24:15 PM
isFeatured            : False
privacyInformationUrl :
informationUrl        :
owner                 : Microsoft
developer             : Microsoft
notes                 :
publishingState       : published
largeIcon             : @{type=image/png; value=iVBORw0KGgoAAAANSUhEUgAAAF0AAAAeCAMAAAEOZNKlAAAAAXNSR0IArs4c6QAAAARnQU1
                        BAACxjwv8YQUAAAJhUExURf////7z7/i9qfF1S/KCW/i+qv3q5P/9/PrQwfOMae1RG+s8AOxGDfBtQPWhhPvUx/759/zg1v
                        Wgg+9fLu5WIvKFX/rSxP728/nCr/FyR+tBBvOMaO1UH+1RHOs+AvSScP3u6f/+/v3s5vzg1+xFDO9kNPOOa/i7pvzj2/vWy
                        es9Af76+Pzh2PrTxf/6+ 
etc...
```

Also multiple properties are missing when calling directly via AppID- 
Native APIs:
![image](https://user-images.githubusercontent.com/41792287/48410015-158ba380-e746-11e8-9a03-6737ac73d45e.png)

InPS:
![image](https://user-images.githubusercontent.com/41792287/48410058-3b18ad00-e746-11e8-956f-ac3c26b2a1f0.png)

Thanks

/Maksim

**Comment by rohitramu** [comment]
Interesting, could you please try switching the schema version to beta before running the command?  That's the only difference I see between the raw HTTP call and the SDK call.

```PowerShell
Update-MSGraphEnvironment -SchemaVersion beta
```

This difference in schema version would also account for the difference in returned properties.

**Comment by POF10** [comment]
Hi Rohit,
You are correct and changing schema version to beta made it working same way as via http call. 

Most probably this is off topic already, but still, could you advise if in some future graph api version missing data from v1 vs beta will be included ? Because at the moment we have to use beta version in production environment which is not recommended due to possible breaking changes. :(

Thanks in advance.

**Comment by rohitramu** [comment]
We are constantly working on promoting APIs from "beta" to "v1.0", it is just a matter of time.  We need to be sure that what we publish to "v1.0" will never need to change, since we cannot make any breaking changes in "v1.0".  As soon as we are certain that the API does not need to change, we promote them to "v1.0".

I'm sorry, I don't know when this particular property will be promoted to "v1.0".

I'll close this issue for now since it has been solved, but please feel free to provide more feedback to us via UserVoice.  Your feedback really does get looked at - in fact, this PowerShell SDK is a result of UserVoice feedback!
