### ISSUE TITLE
deviceManagementScripts missing

### ISSUE THREAD

**Issue by POF10** [Microsoft/Intune-PowerShell-SDK#13]
Hi guys,

Not sure if this is right place to complain about below, but still.. 
In graph 1.0 there is missing possibility to get\post to deviceManagement/deviceManagementScripts - no cmdlets and "400 Bad Request" for 'deviceManagementScripts' via Invoke-MSGraphRequest which is expected in this case.. 
Browser debug:
![image](https://user-images.githubusercontent.com/41792287/48615919-d6a25b80-e99a-11e8-842a-31fe8c22250b.png)

v1:
![image](https://user-images.githubusercontent.com/41792287/48615939-e6ba3b00-e99a-11e8-8218-b5d6fbc69dba.png)

Beta:
![image](https://user-images.githubusercontent.com/41792287/48615954-f33e9380-e99a-11e8-9228-6c380eab5177.png)

After switching to beta, I can get\post via http call\Invoke-MSGraphRequest, but this is no bueno. :(
Maybe this resource is called differently in v1.0 or... 
Please advise ?

Thanks. 
/Maksim

**Comment by rohitramu** [comment]
Thanks for raising the issue Maksim.  Cmdlets are only generated for routes in v1.0.  This is why you would need to use Invoke-MSGraphRequest after switching the schema version to beta for this particular route.

Regarding alternatives to "deviceManagement/deviceManagementScripts" in v1.0, I will follow up and get back to you.

**Comment by rohitramu** [comment]
I've followed up with the feature team - this functionality only exists in beta at the moment, meaning cmdlets are not generated for it.

You will need to continue to use the beta schema version with Invoke-MSGraph to upload/retrieve these scripts.

**Comment by cconrado** [comment]
fyi this should be in the notes as this is an important function
