### ISSUE TITLE
Sorry, but we’re having trouble signing you in.

### ISSUE THREAD

**Issue by geektbee** [Microsoft/Intune-PowerShell-SDK#148]
Ever since May 07, 2024, our system has been getting an error when attempting to run `Connect-MSGraph -PSCredential $creds`. The error is:
```
AADSTS700016: Application with identifier '<GUID-REDACTED>' was not found in the directory '<COMPANY-INITIALS-REDACTED>'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
```
(Replace the REDEACTED tags with real data in your mind, please, because there really is something legit there)

We can clearly see the application in the Enterprise Applications section of the Azure portal. We can see the account that we are using has permission in the "Users and Groups" tab. We can see the failed sign-in attempt in the logs on this application with this Application ID in the "Sign-In Logs". This is very strange, because it has logged a message saying that it can't find itself, then saved the log to itself that it can't find itself. 

We have attempted to `Remove-Module` and re-`Install-Module`, as well as re-run the `Connect-MSGraph -AdminConsent` cmd. The message returns the same every time and the Enterprise Application's Sign-In Logs logs it.

What other data do you need from us to help resolve this?

![image](https://github.com/microsoft/Intune-PowerShell-SDK/assets/16610859/63f2bc6b-eadd-4b19-ab38-5bab5ed9d4db)

![image](https://github.com/microsoft/Intune-PowerShell-SDK/assets/16610859/e64345df-70f5-4333-a125-056092acc6ed)

**Comment by weyCC81** [comment]
> Could this be related to?: https://github.com/microsoftgraph/powershell-intune-samples/issues/245
> @nsoy @rohitramu 

@tfosmark Can you email the C+L governance team about this repo ownership?

Solution: https://learn.microsoft.com/en-us/answers/questions/1659638/weve-detected-a-microsoft-intune-powershell-script

**Comment by geektbee** [comment]
@weyCC81 
Ah, I see. Thank you for your guidance on all this!!

**Comment by tfosmark** [comment]
@weyCC81 I'm not clear on your question. Are you referencing the microsoft/Intune-PowerShell-SDK repo, or the microsoftgraph/powershell-intune-samples repo? What's the governance-specific concern?
