### ISSUE TITLE
Remove-DeviceAppManagement_MobileApps : 403 Forbidden

### ISSUE THREAD

**Issue by vanyuale** [Microsoft/Intune-PowerShell-SDK#15]
I am getting following error running cmdlet under GA account - Remove-DeviceAppManagement_MobileApps. In Intune Portal (portal.azure.com) i can remove app without any issues.

Remove-DeviceAppManagement_MobileApps : 403 Forbidden
{
  "error": {
    "code": "Forbidden",
    "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID:
15b23f11-1eef-4818-9589-ef69e3d5cfed - Url:
https://<tenant>.manage.microsoft.com/StatelessAppMetadataFEService/deviceAppManagement/mobileApps%28%27eedc0aeb-ec3f-4d32-aa7e-7036265c2007%27%29?api-version=2018-03-22\",\r\n 
\"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
    "innerError": {
      "request-id": "15b23f11-1eef-4818-9589-ef69e3d5cfed",
      "date": "2018-12-04T12:15:17"
    }
  }
}
At line:1 char:1
+ Remove-DeviceAppManagement_MobileApps -mobileAppId "eedc0aeb-ec3f-4d3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Remove-DeviceAppManagement_MobileApps], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Remove_DeviceAppManagement_MobileApps

**Comment by nsoy** [comment]
Try the latest version 6.1902.1.10 and see if you can repro this.
$deviceSet = Get-IntuneManagedDevice

$deviceSet[$yourDeviceIndex] | Remove-IntuneManagedDevice
