### ISSUE TITLE
Update README.md "netstandard2.0" folder reference

### ISSUE THREAD

**Issue by adrianwells** [Microsoft/Intune-PowerShell-SDK#17]
Hello.  README.md references extract the "netstandard2.0" folder as a step however that folder is noted as being missing in the current [Preview 3 release](https://github.com/Microsoft/Intune-PowerShell-SDK/releases/tag/Preview3).  Possible to update the README.md to reflect this reality?

**Comment by nsoy** [comment]
Thanks for reviewing it. Let me get that fixed.

**Comment by nsoy** [comment]
This is now fixed.

**Comment by adrianwells** [comment]
@nsoy - thank you, you may want to close out the [Pull Request](https://github.com/Microsoft/Intune-PowerShell-SDK/pull/18) that I submitted for this.
