### ISSUE TITLE
Import-Module : Could not load file or assembly

### ISSUE THREAD

**Issue by adrianwells** [Microsoft/Intune-PowerShell-SDK#19]
Experiencing the similar experience issue #2 when attempting to load the module `Import-Module ./Microsoft.Graph.Intune.psd1`

Results in an error:

```
Intune-PowerShell-SDK\6.1902.00745.0001-release-97194499-net471\drop\outputs\build\Release\net471\Microsoft.Intune.PowerShellGraphSDK.dll' or one of its dependencies. Operation is not supported. (Exception
from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module ./Microsoft.Graph.Intune.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

```

with Release Preview 3, however, unblocking the `net471\Microsoft.Intune.PowerShellGraphSDK.dll` file is not yet resolving this error. Tried with elevated privileges. Working with Windows 10 Version 1803 with .NET framework version 4.7.2 (release 461808).  Other suggestions to resolve?

**Comment by nsoy** [comment]
looking..

**Comment by nsoy** [comment]
See if the netstandard2.0 version works for you. I have created a separate redistributable for dot net core.
https://github.com/Microsoft/Intune-PowerShell-SDK/releases/tag/Preview3-netstandard2.0

**Comment by adrianwells** [comment]
@nsoy Thanks for the reply, however, seeing the same result so far with the same error message:

```
Intune-PowerShell-SDK\6.1902.00745.0001-release-97194499-netstandard2.0\drop\outputs\build\Release\netstandard2.0\Microsoft.Intune.PowerShellGraphSDK.dll' or one of its dependencies. Operation is not
supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module ./Microsoft.Graph.Intune.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Unblocked the `Microsoft.Intune.PowerShellGraphSDK.dll file` as directed in the readme.md. Other suggestions?

**Comment by adrianwells** [comment]
@nsoy - trying again with a Priveledged account, it appears the netstandard2.0 version is now loading:


```
Intune-PowerShell-SDK\6.1902.00745.0001-release-97194499-netstandard2.0\drop\outputs\build\Release\netstandard2.0> get-module -name Microsoft.Graph.Intune

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     6.1902.0.1 Microsoft.Graph.Intune              {Connect-MSGraph, Get-AADGroup, Get-AADGroupCreatedOnBehalfOf, Get-AADGroupCreatedOnBehalfOfReference...}
```

Maybe worth adding a few notes in the Readme or elsewhere about this requirement? Or add a check for whether the PowerShell session has proper rights?

**Comment by adrianwells** [comment]
@nsoy, FYI - the prior comment is for the GitHub prelease version. The most recent version (1902) from PowerShell gallery looks to be working well and does not appear to require privileged access.

**Comment by nsoy** [comment]
I have pushed the module to powershell gallery - try install-module and report issues loading assemblies if any. Thanks!
