### ISSUE TITLE
Could not load file of assembly... 

### ISSUE THREAD

**Issue by kevsully** [Microsoft/Intune-PowerShell-SDK#2]
> PS C:\scripts\net471> import-module .\Microsoft.Graph.Intune.psd1
import-module : Could not load file or assembly 'file:///C:\scripts\net471\Microsoft.Intune.PowerShellGraphSDK.dll' or one of its 
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ import-module .\Microsoft.Graph.Intune.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

The extract seems fine and the file is present... I'm trying to setup the module here for the first time.

Kevin

**Comment by davefalkus** [comment]
Hi @kevsully ,

Can you unblock the file Microsoft.Intune.PowerShellGraphSDK.dll by right clicking the file - Properties and then unblock and then try the import again?

Thanks

Dave

**Comment by kevsully** [comment]
thanks Dave, apologies. All good here. That comment is in the doc. Sorry for confusion.

**Comment by adrianwells** [comment]
@kevsully  and @davefalkus - Experiencing the same experience issue when attempting to load the module `Import-Module ./Microsoft.Graph.Intune.psd1`

Errors with

```
Intune-PowerShell-SDK\6.1902.00745.0001-release-97194499-net471\drop\outputs\build\Release\net471\Microsoft.Intune.PowerShellGraphSDK.dll' or one of its dependencies. Operation is not supported. (Exception
from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module ./Microsoft.Graph.Intune.psd1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

```

with Release Preview 3, however, unblocking the `net471\Microsoft.Intune.PowerShellGraphSDK.dll` file is not yet resolving this error. Tried with elevated privileges. Working Windows 10 Version 1803 with .NET framework version 4.7.2 (release 461808).  Other suggestions to resolve?
