### ISSUE TITLE
Get-IntuneManagedDevice do not bing all device data, userPrincipalName and EmailAddress properties come blank

### ISSUE THREAD

**Issue by LeoniSantos** [Microsoft/Intune-PowerShell-SDK#24]
Hello the cmdlet Get-IntuneManagedDevice do not bing all device data, userPrincipalName and EmailAddress properties come blank, but on intune console this information exist.

is that the expected behavior? 

below follow the command line
Get-IntuneManagedDevice -managedDeviceId "850c085b-deb0-46f8-a9c3-ac05f8f9bc26"

**Comment by nsoy** [comment]
See if this helps 
Get-IntuneManagedDevice | where { $_.id -eq '850c085b-deb0-46f8-a9c3-ac05f8f9bc26'
@roramu - looks like there is an issue here.

**Comment by LeoniSantos** [comment]
Hello Rohit,

I have tried this approach either, but there is no results back, with this command looks like device was not found based on filter, also below you can see on debug option that the API response return the values as null.

![image](https://user-images.githubusercontent.com/44469068/52581598-48f7d000-2e12-11e9-9532-0b1722722281.png)

**Comment by LeoniSantos** [comment]
Hello Rohit, just for information i got able to retrive the information that i need, but i went to another approach and is not fancy but works, so i can get the UPN from user to perfom some automations.

anyway would be nice to have it working in the standard cmdlet

$results = Invoke-MSGraphRequest -Url "https://graph.microsoft.com/$graphApiVersion/$($Resource)" -HttpMethod GET
$results.userId
$User = Get-AzureADUser -ObjectId $results.userId
$UPN = $User.UserPrincipalName

**Comment by roramu** [comment]
Leoni, I'm glad you found a workaround, and thank you for posting it here!

I tried making the `Get-IntuneManagedDevice` call, and found that UPNs were returned for the Windows devices in my test tenant that have had a user log in at least once.  I'm not sure whether the UPN value is returned from Intune for all device types.  I will check this and get back to you.

Also, a quick tip that might improve your experience with the Intune cmdlets: when using `Invoke-MSGraphRequest`, you can set the Graph schema version to apply to all subsequent calls, and then provide just the route to the `Url` parameter (instead of the full URL).  For example:
```PowerShell
Update-MSGraphEnvironment -SchemaVersion 'beta'
$myDevicesThroughBeta = Invoke-MSGraphRequest -Url 'deviceManagement/managedDevices'
$myAppsThroughBeta = Invoke-MSGraphRequest -Url 'deviceAppManagement/mobileApps'
```

**Comment by LeoniSantos** [comment]
cool Thanks for the feedback this is really helpfull as you can use it exacly as you get it on documentation.

will do that

**Comment by pekohub** [comment]
for people struggling with a way to search for Intune devides by their id here's how:

`Get-AzureADDevice -Filter "deviceId eq guid'26ceedbb-0f1a-432a-bf59-e78a2864fdbb'"`

see [this thread](https://github.com/Azure/azure-docs-powershell-azuread/issues/216) for reference.

**Comment by Nightfearz** [comment]
I struggled with this for some time but this worked:

(Get-IntuneManagedDevice).value

This returned all the device objects in Intune. I was using it as part of a script to identify the primary user of a intune enrolled device so I combined this with the following:

$Computer = $env:COMPUTERNAME
$Get_MyDevice_Infos = (Get-IntuneManagedDevice).value | where-object {$_.devicename -eq $Computer}.....
