### ISSUE TITLE
Get-DeviceManagement_DeviceConfigurations not returning anything even though DeviceConfigurations exist

### ISSUE THREAD

**Issue by vreddi** [Microsoft/Intune-PowerShell-SDK#26]
Able to get 384 (less than one default page size) of device configurations back when I hit the following API:
https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations
![image](https://user-images.githubusercontent.com/6148930/53041527-10bb4780-3439-11e9-8dcb-00c17c1c3f08.png)

Unable to get any results back using just the cmdlet: Get-DeviceManagement_DeviceConfigurations.
![tempsnip](https://user-images.githubusercontent.com/6148930/53041793-b2429900-3439-11e9-87ff-6e9bad6251ee.png)

**Comment by davefalkus** [comment]
There is an update the module, can you try with Get-IntuneDeviceConfigurationPolicy?

![image](https://user-images.githubusercontent.com/20442367/54077558-019a1d80-42b2-11e9-9b66-035acd6e1e2d.png)

Just tried against my tenant and it returned all configuration policies.

**Comment by davefalkus** [comment]
Please reopen issue if still occuring with updated module.
