### ISSUE TITLE
Get-IntuneMobileApp does not retuen application version

### ISSUE THREAD

**Issue by AKugaseelan** [Microsoft/Intune-PowerShell-SDK#30]
When running, the version property is always empty.

**Comment by davefalkus** [comment]
To clarify, do you mean version that displayed in the UI?

![image](https://user-images.githubusercontent.com/20442367/54077464-710f0d80-42b0-11e9-846c-133fec173fff.png)

If so the attribute is productversion:
Get-IntuneMobileApp | Where-Object { $_.productversion -ne $null }

**Comment by AKugaseelan** [comment]
Yes, I meant the version, displayed in the UI. Thanks for the clarification.

**Comment by davefalkus** [comment]
Thanks for clarifying will close the issue.
