### ISSUE TITLE
[Q] Why break module de facto naming standard with punctuation?

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/Intune-PowerShell-SDK#33]
This is the only module I've ever seen where the "parent" module has puctuations (".") in the main name. This is confusing, and breaks the naming standard used by most (all?) other modules, also from Microsoft.

- Why is that? Is there a good reason?
- Any hope of a name change to comply with probably 99% of the other modules available from PowerShellGallery?

**Comment by corbob** [comment]
Possible answer: Microsoft Modules are not uncommon to have this naming convention:

![image](https://user-images.githubusercontent.com/30301021/57654650-94448a80-7589-11e9-94ee-4c37f0b97fb7.png)

**Comment by rohitramu** [comment]
Thanks for raising the question @o-l-a-v.  @corbob, that is exactly correct.  When searching for modules, this naming convention makes it much easier to categorize and find them (after sorting by name).
