### ISSUE TITLE
Can't use module on macOS using Visual Studio Code

### ISSUE THREAD

**Issue by vanyuale** [Microsoft/Intune-PowerShell-SDK#5]
Hey,

i tried to use this module on macOS and successfully imported module, connected to Graph, but after it's failing with following error:

```
 PS /Users/vanyuale> Get-DeviceAppManagement_MobileApps
Get-DeviceAppManagement_MobileApps : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific
file. (Exception from HRESULT: 0x80131621)
At line:1 char:1
+ Get-DeviceAppManagement_MobileApps
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-DeviceAppManagement_MobileApps], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_DeviceAppManagement_MobileApps
```

I tried to install package (Install-Package Newtonsoft.Json), but that didn't help. Is there anything i'm missing or that is not suppose to work.

Thank you.

**Comment by rohitramu** [comment]
Thanks for reporting this, I'm investigating it now.  I'll let you know what I find.

**Comment by rohitramu** [comment]
I wasn't able to reproduce this issue using a MacBook Air running macOS High Sierra.  I was able to load the module and login using the shell in Visual Studio Code.

Could you please run this command just before you run "Import-Module" and share the output?
```PowerShell
[AppDomain]::CurrentDomain.GetAssemblies() | Sort-Object -Property FullName
```

**Comment by vanyuale** [comment]
Sure, but i also was able to Import module. Problem is with executing any commands after.

`PS /Users/vanyuale> [AppDomain]::CurrentDomain.GetAssemblies() | Sort-Object -Property FullName

GAC    Version        Location
---    -------        --------
False  v4.0.30319
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.ApplicationInsights.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.CSharp.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.Management.Infrastructure.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.PowerShell.Commands.Manage...
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.PowerShell.Commands.Utilit...
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.PowerShell.ConsoleHost.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.PowerShell.CoreCLR.Assembl...
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.PowerShell.PSReadLine.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.PowerShell.Security.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.Win32.Primitives.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Microsoft.Win32.Registry.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/netstandard.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/Newtonsoft.Json.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/powershell.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Collections.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Collections.Concurrent.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Collections.NonGeneric.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Collections.Specialized.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.ComponentModel.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.ComponentModel.Primitives.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.ComponentModel.TypeConverter.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Console.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Data.Common.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Diagnostics.Debug.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Diagnostics.DiagnosticSource.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Diagnostics.Process.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Diagnostics.Tools.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Diagnostics.TraceSource.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Diagnostics.Tracing.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Dynamic.Runtime.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Globalization.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.IO.Compression.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.IO.FileSystem.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.IO.FileSystem.AccessControl.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.IO.FileSystem.DriveInfo.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Linq.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Linq.Expressions.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Management.Automation.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Net.Http.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Net.Mail.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Net.NetworkInformation.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Net.Primitives.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.ObjectModel.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Private.CoreLib.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Private.Uri.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Private.Xml.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Private.Xml.Linq.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Reflection.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Reflection.Emit.ILGeneration.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Reflection.Emit.Lightweight.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Reflection.Extensions.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Reflection.Primitives.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Resources.ResourceManager.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Runtime.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Runtime.Extensions.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Runtime.InteropServices.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Runtime.InteropServices.Runti...
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Runtime.Loader.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Runtime.Numerics.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Security.AccessControl.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Security.Cryptography.Encodin...
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Security.Cryptography.X509Cer...
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Security.Principal.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Security.Principal.Windows.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Text.Encoding.Extensions.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Text.RegularExpressions.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Threading.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Threading.AccessControl.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Threading.Tasks.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Threading.Tasks.Parallel.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Threading.Thread.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Xml.ReaderWriter.dll
False  v4.0.30319     /usr/local/microsoft/powershell/6.0.0-beta.5/System.Xml.XDocument.dll`

**Comment by rohitramu** [comment]
I was able to execute the following:
```PowerShell
Import-Module ./Microsoft.Graph.Intune.psd1
Connect-MSGraph
Get-DeviceAppManagement_MobileApps
```

The only difference I see between your loaded assemblies and mine is that you're using a beta version of PowerShell (v6.0.0-beta.5).  Could you please try again after installing the latest stable version of PowerShell 6?

**Comment by vanyuale** [comment]
Indeed stable version works. 

Thank you!

**Comment by rohitramu** [comment]
Good to hear it worked!
