### ISSUE TITLE
Invoke-IntuneManagedDeviceWipeDevice should not require macOsUnlockCode as mandatory

### ISSUE THREAD

**Issue by patlewis-MSFT** [microsoft/Intune-PowerShell-SDK#50]
One of the parameters for Invoke-IntuneManagedDeviceWipeDevice is not applicable to Android or Win devices but still requires a macOsUnlockCode.

See ManagedDevices.cs
        [Parameter(**Mandatory = true,** ValueFromPipelineByPropertyName = true, HelpMessage = @"The &quot;macOsUnlockCode&quot; action parameter of type &quot;Edm.String&quot;.")]
        public System.String macOsUnlockCode { get; set; }

**Comment by rohitramu** [comment]
Duplicate of #51.
