### ISSUE TITLE
New-IntuneMobileApp for Office 365

### ISSUE THREAD

**Issue by JoshuaMelo** [microsoft/Intune-PowerShell-SDK#52]
Hi how do I publish the Office 365 suite for Windows in Intune? I can see that you can see the info from Get-IntuneMobileApp:
<img width="492" alt="Capture" src="https://user-images.githubusercontent.com/25836748/60842791-fb09ad00-a1a2-11e9-9393-90e78ee1e07b.PNG">

But the New-IntuneMobileApp does not allow me to upload with similar parameters. Am I using the wrong cmdlet?

**Comment by rohitramu** [comment]
As of July 29th 2019, it looks like only the "macOSOfficeSuiteApp" entity type is available in the v1.0 schema.  The "officeSuiteApp" object that you see in your results was probably created through the beta schema, where that entity type does exist.
