### ISSUE TITLE
Examples for using Get-MSGraphAllPages?

### ISSUE THREAD

**Issue by ladcock19** [microsoft/Intune-PowerShell-SDK#53]
I'm trying to call the cmdlet Get-IntuneManagedDevice and my environment has more than 1000 devices so only the first 1000 are retrieved.

I'm trying to understand how to use the data and the @odata.nextLink parameter to loop through all devices.  In my reading, there's a Get-MSGraphAllPages.  What's not clear to me is why is there a 'NextLink' parameter when the cmdlet name implies it retrieves "all" data.

**Comment by rohitramu** [comment]
The `Get-MSGraphAllPages` cmdlet is designed to take the result objects that need to be paged.  For example:

```csharp
$allDevicesInTenant = Get-IntuneManagedDevice | Get-MSGraphAllPages
```

This will retrieve all Intune devices in your tenant.

**Comment by rohitramu** [comment]
The `Get-MSGraphAllPages` cmdlet is designed to take the result objects that need to be paged.  For example:

```csharp
$allDevicesInTenant = Get-IntuneManagedDevice | Get-MSGraphAllPages
```

This will retrieve all Intune devices in your tenant.

**Comment by benhaslett** [comment]
Thanks! This post got me over a business problem I'd been stuck on for 2 years!

**Comment by 1Barry54** [comment]
Hey
