### ISSUE TITLE
Can't retrieve Conditional Access settings.

### ISSUE THREAD

**Issue by lvillesystemsjockey** [Microsoft/Intune-PowerShell-SDK#9]
Output below.  I can retrieve other settings without issue.

Get-DeviceManagement_ConditionalAccessSettings
Get-DeviceManagement_ConditionalAccessSettings : 400 Bad Request
{
  "error": {
    "code": "BadRequest",
    "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 9c3f35ca-e255-4a1e-aa55-6b33f64af339 - Url: 
https://fef.msua05.manage.microsoft.com/StatelessOnboardingService/deviceManagement/conditionalAccessSettings?api-version=2018-01-11\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  
\"HttpHeaders\": \"{}\"\r\n}",
    "innerError": {
      "request-id": "**************************",
      "date": "2018-10-23T14:11:16"
    }
  }
}
At line:1 char:1
+ Get-DeviceManagement_ConditionalAccessSettings
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (@{Request=; Response=}:PSObject) [Get-DeviceManag...lAccessSettings], HttpRequestException
    + FullyQualifiedErrorId : PowerShellGraphSDK_HttpRequestError,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Get_DeviceManagement_ConditionalAccessSettings

**Comment by rohitramu** [comment]
The `Get-DeviceManagement_ConditionalAccessSettings` cmdlet returns an "onPremisesConditionalAccessSettings" object.  To clarify, are you intending to get **on-premises** settings for conditional access?

**Comment by rohitramu** [comment]
I will close this since it has been inactive for a while.  Please reopen this if you are still facing issues.

**Comment by lvillesystemsjockey** [comment]
Thank you, I was wrong in understanding this was Azure Conditional Access.  Please close.  thank you.
